### ISSUE TITLE
SanchoNet Cardano DB Sync does not parse conway-genesis.json under docker

### ISSUE THREAD

**Issue by placek** [IntersectMBO/cardano-db-sync#1629]
**OS**
Linux, NixOS 23.11.2936.428544ae95ee (Tapir)

**Versions**
DBSync: `ghcr.io/intersectmbo/cardano-db-sync:sancho-4-0-0` (docker image)
PostgreSQL version: `postgres:15-alpine` (docker image)

**Build/Install Method**
Fragment of the docker compose file:
```
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:8.8.0-pre
    entrypoint:
      - "cardano-node"
      - "run"
      - "--topology"
      - "/configuration/topology.json"
      - "--database-path"
      - "/data/db"
      - "--socket-path"
      - "/ipc/node.socket"
      - "--host-addr"
      - "0.0.0.0"
      - "--port"
      - "3001"
      - "--config"
      - "/configuration/config.json"
      - "+RTS"
      - "-N2"
      - "-I0"
      - "-A16m"
      - "-qg"
      - "-qb"
      - "--disable-delayed-os-memory-return"
      - "-RTS"
    environment:
      - NETWORK=${CARDANO_NETWORK:-sanchonet}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
      - /home/ubuntu/config/cardano-node:/configuration
    restart: always

  cardano-db-sync:
    image: ghcr.io/intersectmbo/cardano-db-sync:sancho-4-0-0
    environment:
      - NETWORK=${CARDANO_NETWORK:-sanchonet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
      - EXTRA_DB_SYNC_ARGS=${EXTRA_DB_SYNC_ARGS:-}
    depends_on:
      cardano-node:
        condition: service_healthy
      postgres:
        condition: service_healthy
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc
    restart: always
```

**Run method**
`docker-compose up`

**Additional context**
Clear, new volumes, no previous DB state.

**Problem Report**
The DBSync throws this info in the logs:
```
dev-sanchonet-cardano-db-sync-1  | cardano-db-sync: Error SNErrConwayConfig: Failed reading Conway genesis file "/nix/store/13205wb8d217bspljhalb6wdxjs50d6p-conway-genesis.json": "There was an error parsing the genesis file: /nix/store/13205wb8d217bspljhalb6wdxjs50d6p-conway-genesis.json Error: Error in $.poolVotingThresholds: key \"motionNoConfidence\" not found"
```

This DBSync's image has it's own configuration files for sanchonet network incorporated as a docker context.
It seems that in previous version of DBSync (i.e.
ghcr.io/intersectmbo/cardano-db-sync:sancho-4-0-0`) those files were fine and there was no need to apply any specific, additional configuration to execute dbsync, so the previous version worked just fine.
This version however seems to have those files corrupted for some reason (maybe it's a bug in the image, idk).

When I'm feeding a correct configuration files from https://book.world.dev.cardano.org/env-sanchonet.html (by providing the volume with those files and chenging three scripts to adjust that) the DBSync executes normally and communicates properly with Cardano Node.
