### ISSUE TITLE
`docker-compose` does not work for `sanchonet` with node `9.0.0` and db-sync `13.3.0.0`

### ISSUE THREAD

**Issue by ArturWieczorek** [IntersectMBO/cardano-db-sync#1773]
`NETWORK=sanchonet docker compose up && docker compose logs -f`
```sh
cardano-db-sync-cardano-node-1     | CardanoProtocolInstantiationError (CardanoProtocolInstantiationConwayGenesisReadError (GenesisHashMismatch "7c2006fa6be472c3a04b693810f89bfbefe99625b12b9d400d17a7072e5961d6" "79766b0c18076e9abefc806526714f30d42b14dba9f187fb316bd4e70c815ef4"))
cardano-db-sync-cardano-node-1     | 
cardano-db-sync-cardano-node-1 exited with code 1
```

```
docker-compose:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:9.0.0
...
  cardano-db-sync:
    image: ghcr.io/intersectmbo/cardano-db-sync:13.3.0.0
```

`preprod` works fine.
